// Copyright 2018-2022 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= KHR_materials_clearcoat
:tmtitle: pass:q,r[^™^]
:regtitle: pass:q,r[^®^]
The Khronos{regtitle} 3D Formats Working Group
:data-uri:
:icons: font
:toc2:
:toclevels: 10
:sectnumlevels: 10
:max-width: 100%
:numbered:
:source-highlighter: coderay
:docinfo: shared-head
:docinfodir: ../..
:stem:

// :xrefstyle: short
// :listing-caption: Listing
:leveloffset: 1

= Contributors

  * Norbert Nopper, UX3D https://twitter.com/UX3DGpuSoftware[@UX3DGpuSoftware]
  * Tobias Haeussler, Dassault Systemes https://github.com/proog128[@proog128]
  * Alexey Knyazev https://github.com/lexaknyazev[@lexaknyazev]
  * Don McCurdy, Google https://twitter.com/donrmccurdy[@donrmccurdy]
  * Sebastien Vandenberghe, Microsoft https://twitter.com/sebavanjs[@sebavanjs]
  * Romain Guy, Google https://twitter.com/romainguy[@romainguy]
  * Ed Mackey, AGI https://twitter.com/emackey[@emackey]
  * Alex Wood, AGI https://twitter.com/abwood[@abwood]

Copyright 2018-2022 The Khronos Group Inc. All Rights Reserved. glTF is a trademark of The Khronos Group Inc.
See <<full-copyright, the appendix>> for the full Khronos Copyright Statement.

= Status

Complete, Ratified by the Khronos Group

= Dependencies

Written against the glTF 2.0 spec.

= Exclusions

  * This extension must not be used on a material that also uses `KHR_materials_pbrSpecularGlossiness`.
  * This extension must not be used on a material that also uses `KHR_materials_unlit`.

= Overview

This extension defines a clear coating that can be layered on top of an existing glTF material definition.  A clear coat is a common technique used in Physically-Based Rendering to represent a protective layer applied to a base material.  See <<theory-documentation-and-implementations, Theory, Documentation and Implementations>>.

= Extending Materials

The PBR clearcoat materials are defined by adding the `KHR_materials_clearcoat` extension to any compatible glTF material (excluding those listed above).  For example, the following defines a material like varnish using clearcoat parameters.

[source,json]
----
{
    "materials": [
        {
            "name": "varnish",
            "extensions": {
                "KHR_materials_clearcoat": {
                    "clearcoatFactor": 1.0
                }
            }
        }
    ]
}
----

== Clearcoat

The following parameters are contributed by the `KHR_materials_clearcoat` extension:

[options="header"]
|====
|                             | Type                                                                                               | Description                                            | Required
| *clearcoatFactor*           | `number`                                                                                           | The clearcoat layer intensity.                         | No, default: `0.0`
| *clearcoatTexture*          | https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-textureinfo[`textureInfo`] | The clearcoat layer intensity texture.                 | No
| *clearcoatRoughnessFactor*  | `number`                                                                                           | The clearcoat layer roughness.                         | No, default: `0.0`
| *clearcoatRoughnessTexture* | https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-textureinfo[`textureInfo`] | The clearcoat layer roughness texture.                 | No
| *clearcoatNormalTexture*    | https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-material-normaltextureinfo[`normalTextureInfo`] | The clearcoat normal map texture. | No
|====

If `clearcoatFactor` (in the extension) is zero, the whole clearcoat layer is disabled.

The values for clearcoat layer intensity and clearcoat roughness can be defined using factors, textures, or both. If the `clearcoatTexture` or `clearcoatRoughnessTexture` is not given, respective texture components are assumed to have a value of 1.0. All clearcoat textures contain RGB components in linear space. If both factors and textures are present, the factor value acts as a linear multiplier for the corresponding texture values.

[source]
----
clearcoat = clearcoatFactor * clearcoatTexture.r
clearcoatRoughness = clearcoatRoughnessFactor * clearcoatRoughnessTexture.g
----

If `clearcoatNormalTexture` is not given, no normal mapping is applied to the clear coat layer, even if normal mapping is applied to the base material.  Otherwise, `clearcoatNormalTexture` may be a reference to the same normal map used by the base material, or any other compatible normal map.

The clearcoat effect is modeled via a microfacet BRDF. The BRDF is layered on top of the glTF 2.0 Metallic-Roughness material, including emission and all extensions, using a new `fresnel_coat` function:

[source]
----
# from glTF 2.0 Metallic-Roughness material (core)
material = mix(dielectric_brdf, metal_brdf, metallic)

# clearcoat
clearcoat_brdf = specular_brdf(
  normal = clearcoatNormal,
  {alpha} = clearcoatRoughness^2)

# layering
coated_material =
  fresnel_coat(
    normal = clearcoatNormal,
    ior = 1.5,
    weight = clearcoat,
    base = material,
    layer = clearcoat_brdf)
----

The `fresnel_coat` function adds a BRDF as a layer on top of another BSDF according to `weight` and a Fresnel term. The layer is weighted with `weight*fresnel(ior)`. The base is weighted with `1-(weight*fresnel(ior))`. `normal` is a float3 vector that affects the top layer, but not the base.

== Implementation

_This section is non-normative._

Implementations of the BRDF or the layering operator can vary based on device performance and resource constraints.

=== Clearcoat BRDF

The specular BRDF for the clearcoat layer `clearcoat_brdf` is computed using the specular term from the glTF 2.0 Metallic-Roughness material, defined in https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#appendix-b-brdf-implementation[Appendix B]. Roughness and normal are taken from `clearcoatNormal` and `clearcoatRoughness`.

=== Layering

The `fresnel_coat` function is computed using the Schlick Fresnel term from the glTF 2.0 Metallic-Roughness material, defined in https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#appendix-b-brdf-implementation[Appendix B].

[source]
----
function fresnel_coat(normal, ior, weight, base, layer) {
  f0 = ((1-ior)/(1+ior))^2
  fr = f0 + (1 - f0)*(1 - abs(NdotV))^5   // N = normal
  return mix(base, layer, weight * fr)
}
----

Applying the functions we arrive at the coated material

[source]
----
coated_material = mix(material, clearcoat_brdf(clearcoatRughness^2), clearcoat * (0.04 + (1 - 0.04) * (1 - NdotV)^5))
----

and finally, substituting and simplifying, using some symbols from https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#appendix-b-brdf-implementation[Appendix B] and `Nc` for the clearcoat normal:

[source]
----
clearcoatFresnel = 0.04 + (1 - 0.04) * (1 - abs(VdotNc))^5
clearcoatAlpha = clearcoatRoughness^2

f_clearcoat = clearcoatFresnel * D(clearcoatAlpha) * G / (4 * abs(VdotNc) * abs(LdotNc))

coated_material = (f_diffuse + f_specular) * (1 - clearcoat * clearcoatFresnel) +
                  f_clearcoat * clearcoat
----

=== Emission

The clearcoat layer is on top of emission in the layering stack. Consequently, the emission is darkened by the Fresnel term.

[source]
----
coated_emission = emission * (0.04 + (1 - 0.04) * (1 - NdotV)^5)
----

=== Discussion

In order to make the material energy conserving with a simple layering function, we compute the microfacet Fresnel term with `NdotV` instead of `VdotH`. That means that we ignore the orientation of the microsurface. As the clearcoat roughness is usually very low the microfacets orientation is very close to the normal direction, and `NdotV {almostequal} NdotL`.

The simple layering function ignores many effects that occur between clearcoat and base layer. For example:

  * The clearcoat layer is assumed to be infinitely thin. There is no refraction.
  * The index of refraction of clearcoat and base layer do not influence each other. The Fresnel terms are computed independently.
  * There is no scattering between layers.
  * There is no diffraction.

More sophisticated layering techniques that improve the accuracy of the renderings are described in https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#appendix-b-brdf-implementation[Appendix B].

= glTF Schema Updates

  * *JSON schema*: link:schema/glTF.KHR_materials_clearcoat.schema.json[glTF.KHR_materials_clearcoat.schema.json]

= References

[[theory-documentation-and-implementations]]
== Theory, Documentation and Implementations

  * https://autodesk.github.io/standard-surface/#closures/coating[Autodesk Standard Surface - Coating]
  * https://www.xrite.com/-/media/xrite/files/whitepaper_pdfs/axf/axf_whitepaper_en.pdf[AxF - Appearance exchange Format]
  * https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html[Blender Principled BSDF]
  * https://github.com/wdas/brdf/blob/master/src/brdfs/disney.brdf[Disney BRDF Explorer - disney.brdf]
  * https://dassaultsystemes-technology.github.io/EnterprisePBRShadingModel/spec-2020x.md.html#components/clearcoat[Enterprise PBR Shading Model - Clearcoat]
  * https://google.github.io/filament/Materials.md.html#materialmodels/litmodel/clearcoat[Filament Material models - Clear coat]
  * https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf[Physically-Based Shading at Disney]
  * https://docs.substance3d.com/spdoc/version-2018-3-172823522.html#Version2018.3-UpdatedClearCoatShader[Substance Painter - Updated Clear Coat Shader]
  * https://academy.substance3d.com/courses/the-pbr-guide-part-1[THE PBR GUIDE BY ALLEGORITHMIC - PART 1]
  * https://academy.substance3d.com/courses/the-pbr-guide-part-2[THE PBR GUIDE BY ALLEGORITHMIC - PART 2]
  * https://docs.unrealengine.com/en-US/Engine/Rendering/Materials/MaterialInputs/index.html#clearcoat[Unreal Engine 4 Material - Clear Coat]

:numbered!:

[appendix]
[[full-copyright]]
= Full Khronos Copyright Statement

:copyyears: 2018-2022
include::../../speccopyright.txt[]
